pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'GitHub', url: 'https://github.com/cyb-swap/shop-app.git'
            }
        }

        stage('Dependency-Check') {
            steps {
                dependencyCheck additionalArguments: '', odcInstallation: 'dep-check-auto'
                dependencyCheckPublisher pattern: ''
                archiveArtifacts allowEmptyArchive: true, artifacts: 'dependency-check-report.xml', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                sh ' rm -rf dependency-check-report.xml*'
            }
        }
        
        stage('Build Docker Images') {
            steps {
                script {
                    def images = [
                        ["name": "shop_app_app:latest", "path": "app"],
                        ["name": "shop_app_database:latest", "path": "database"],
                        ["name": "shop_app_payment_gateway:latest", "path": "payment_gateway"],
                        ["name": "shop_app_reverse_proxy:latest", "path": "reverse_proxy"]
                    ]
                    
                    for (img in images) {
                        echo "Building Docker image: ${img.name}"
                        docker.build(img.name, img.path)
                    }
                }
            }
        }

        stage('Scan Docker Images with Grype') {
            steps {
                script {
                    def images = [
                        ["name": "shop_app_app:latest", "output": "grype_app_scan.json"],
                        ["name": "shop_app_database:latest", "output": "grype_database_scan.json"],
                        ["name": "shop_app_payment_gateway:latest", "output": "grype_payment_gateway_scan.json"],
                        ["name": "shop_app_reverse_proxy:latest", "output": "grype_reverse_proxy_scan.json"]
                    ]
                    
                    for (img in images) {
                        echo "Running Grype scan on ${img.name}"
                        sh "grype ${img.name} --output json > ${img.output}"

                        // Ensure the output file exists before attempting to read it
                        if (fileExists(img.output)) {
                            echo "Checking vulnerabilities in ${img.output}"
                            def vulnerabilities = readJSON file: img.output
                            if (vulnerabilities.matches) {
                                error("Vulnerabilities found in ${img.name}!")
                            }
                        } else {
                            error("Grype scan output not found for ${img.name}!")
                        }
                    }
                }
            }
        }
        
        stage('SCA') {
            steps {
                script{
                    dir('app/react-app') {
                        sh 'yarn install'
                        snykSecurity(
                            snykInstallation: 'snyk',
                            snykTokenId: '59e68e07-6d49-416b-a4f3-ba4523a0f631',
                            failOnIssues: false,
                        )
                    }
                }
            }
        }
        
        stage('Run Docker Compose') {
            steps {
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
    
    post {
        always {
            script {
                sh 'docker-compose down'
            }
            cleanWs()
        }
    }
}
